insert INTO cities(name) VALUES('Москва');
insert INTO cities(name) VALUES('Санкт-Петербург');
insert INTO cities(name) VALUES('Екатеринбург');
INSERT INTO cities (name) VALUES ('Новосибирск');
INSERT INTO cities (name) VALUES ('Казань');
INSERT INTO cities (name) VALUES ('Челябинск');
INSERT INTO cities (name) VALUES ('Омск');
INSERT INTO cities (name) VALUES ('Самара');
INSERT INTO cities (name) VALUES ('Ростов-на-Дону');
INSERT INTO cities (name) VALUES ('Уфа');
INSERT INTO cities (name) VALUES ('Волгоград');
INSERT INTO cities (name) VALUES ('Красноярск');
INSERT INTO cities (name) VALUES ('Пермь');
INSERT INTO cities (name) VALUES ('Воронеж');
INSERT INTO cities (name) VALUES ('Саратов');
INSERT INTO cities (name) VALUES ('Тольятти');
INSERT INTO cities (name) VALUES ('Ижевск');
INSERT INTO cities (name) VALUES ('Барнаул');
INSERT INTO cities (name) VALUES ('Ульяновск');
INSERT INTO cities (name) VALUES ('Хабаровск');